### ISSUE TITLE
'Before' & 'After' Date Parameters Not Working

### ISSUE THREAD

**Issue by cbgrace** [18F/analytics.usa.gov#1089]
## What kind of issue?
Bug

## User story
The before & after parameters seem to not really do anything, I am only seeing results from the last week. This does not match the behavior outlined in the documentation I found at: https://open.gsa.gov/api/dap/

## Acceptance Criteria
- [ ] 

## Notes
For example, if you notice in the following link, the dates only go back to 2023-12-05:
https://api.gsa.gov/analytics/dap/v1.1/agencies/agriculture/reports/site/data?api_key=DEMO_KEY1&before=2023-12-12&after=2023-11-25
Additionally, the following link returns an empty list:
https://api.gsa.gov/analytics/dap/v1.1/agencies/agriculture/reports/site/data?api_key=DEMO_KEY1&before=2023-12-01&after=2023-11-25
Changing the agency name or report type does not seem to matter either:
https://api.gsa.gov/analytics/dap/v1.1/agencies/interior/reports/download/data?api_key=DEMO_KEY1&before=2023-12-01&after=2023-11-25
https://api.gsa.gov/analytics/dap/v1.1/agencies/state/reports/os/data?api_key=DEMO_KEY1&before=2023-12-01&after=2023-11-25

**Comment by smarina04** [comment]
@cbgrace thank you for reporting this, we recently did an upgrade and some of the older data did not propagate over to the newer database. We believe we have resolved the issue, and ask that you attempt your API queries once more. Please let us know if you see ANYTHING out of the ordinary.

**Comment by jhaese** [comment]
I am also facing this issue, I cannot access data older than 2023-07-31 while I could access data up to 2017 before.

**Comment by jhaese** [comment]
It still does not seem to propagate in v2.0.0, please see for example the following request: https://api.gsa.gov/analytics/dap/v2.0.0/reports/os-browser/data?api_key=DEMO_KEY1&before=2024-02-25

**Comment by levinmr** [comment]
@jhaese @cbgrace 

This issue should be addressed now.  The problem described occurred because data older than 2023 was not migrated as we updated the DAP API.  Data from 2017 to 2024-06-24 should be available in API v1.1

The confusion with API v2 data may be that the data being returned from API v2 is Google Analytics 4 data and API v1.1 returns Universal Analytics data.  

API v2 will only have data going back to when GA4 was implemented in the DAP code (around 2023-08-01) and may be different per agency/domain as GA4 data began being collected when sites included the new DAP code version.
