### ISSUE TITLE
Bounce rate dataset is empty

### ISSUE THREAD

**Issue by cresharper** [18F/analytics.usa.gov#1313]
## What kind of issue?
- [ ] Feature Request?
- [ x] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a <x kind of end user>, I would like to <y thing on the side>, so that I can <z provide the value of the change to the user>.

I can't/don't know how to access bounce rate dataset for treasury. 

per the documentation:

The URL for the API is https://api.gsa.gov/analytics/dap/v2.0.0, and it exposes 3 routes to query data:

```
/reports/<report name>/data
/agencies/<agency name>/reports/<report name>/data
/domain/<domain>/reports/<report name>/data
```

I do bounce rate like this:

https://api.gsa.gov/analytics/dap/v2.0.0/agencies/treasury/reports/bounce_rate/data?api_key=MYAPIKEY

I get nothing, just an empty array. Why?

## Acceptance Criteria
- [ ] - not applicable

**Comment by levinmr** [comment]
The issue with missing data has been resolved.  All documented routes in the API should have data now from August 2024 to the present.

However, there is no documented report for bounce_rate in the [DAP API docs](https://open.gsa.gov/api/dap/).  I do see that bounce_rate is incorrectly noted as a field that can be returned, because none of the reports that the API delivers have this field.

If bounce rate is a desired metric for your purposes, please make a feature request by emailing dap@gsa.gov(mailto:dap@gsa.gov)
