### ISSUE TITLE
No data in chart when moved immediately after midnight - add weekly/yesterday?

### ISSUE THREAD

**Issue by wslack** [18F/analytics.usa.gov#164]
The daily volume tracker blanks itself when viewed at 12:01 AM. We could put in yesterday's volume in light gray as a filler content, or maybe a rolling 7 day average?

**Comment by gbinal** [comment]
How long does that last for? One minute or one hour?  If the former, I'm not sure there's a need.

**Comment by wslack** [comment]
I think I was looking at 12:20 AM, but even then its a very blank graph for most of the evening. https://github.com/GSA/analytics.usa.gov/issues/87 also might inform that.

**Comment by konklone** [comment]
This has come up a few times, and @cew821 in particular has really hated the blank look of that chart in the wee hours. I personally don't think it's worth re-engineering the data production (to keep a "yesterday" and a "today") or the client-side rendering (to display different data during a particular timeframe) to make it a bit more appealing during those hours, since it looks pretty great 80% of the time, during "business hours".

**Comment by gbinal** [comment]
Gotcha.  Definitely see the annoyance at that, even though it's an accurate view.  

That said, I too would advise keeping the project straightforward for now and focus on building out the functionality and data available through it.  The more custom complexity we add at this stage will complicate next steps.

**Comment by tdlowden** [comment]
+1 to @konklone and @gray. Keeping as is for now. Closing.
