### ISSUE TITLE
Brainstorm design changes

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#217]

**Comment by hbillings** [comment]
Here are some initial thoughts. Will share in the DAP channel but would love some feedback!
### **Suggestions**
- **Implement the Draft Web Design Standards**. This would be fairly straightforward. My initial pass suggests that mostly this would involve changing colors and forms, with some small tweaks to fonts.
- **Move Downloads to its own page**, which will give us room to expand that list, and also to elaborate on what's in a given set of data files. I'd also like to more **clearly indicate data formats** (with icons) since it's mixed.
- **Move the disclaimer about time series** from the "About" footer to the time series tabs. (screenshot)
- **Make relationship between "Top Pages"/"Top Domains" and the time series tabs clearer** . This will make it less confusing when the data points change from pages on the "now" tab to domans on the 7- and 3-day tabs. (screenshot)
![screen shot 2016-03-09 at 4 50 07 pm](https://cloud.githubusercontent.com/assets/509309/13885602/4880fe26-ed01-11e5-839e-3d98a256c963.png)

- **Remove bars from "Cities"**. The numbers are all so small that the bars feel visually like extra whitespace. "Cities" could effectively adopt the style used for the country breakdown.
- **Address extra white space**, particularly around the location charts. One potential way to do this would be to break the "US" and "International" bars into their own column on the left, similar to the "Devices" chart above. (screenshot)
<img width="757" alt="screen shot 2016-03-18 at 12 57 21 pm" src="https://cloud.githubusercontent.com/assets/509309/13887316/0e88b2f6-ed09-11e5-8528-e35a7f4001c0.png">
(I also like the idea of breaking these charts down into "US" and "International" charts, with cities nested under "US" the way countries are currently nested under "International." That doesn't help with the whitespace issue, though.)

### **Questions**
- **How useful is the "Visits today" graph?** My first impression is that it's taking up a lot of space for something that essentially just maps when people are awake. Would "Visits in the past 7 days" or something similar be more interesting?
- **Are the device, browser and OS breakdowns over the past 90 days?** I assume so, because they're under that heading, but it's just unclear enough that I think we should make it more obvious if so. (This could be as simple as tightening the whitespace under "There were X visits in the past 90 days.)
- **Are the percentages displayed for "Cities" a percentage of all traffic, or a percentage of US-based traffic?** Same question for "Countries" and "International."
- Based on the conversations recently, **are there other charts that we want to add to this page?**

**Comment by hbillings** [comment]
Actually, the more I think about it, the more I don't like my suggestion for the whitespace issue. That just moves the whitespace around instead of eliminating it. I'll keep thinking on that.

**Comment by gbinal** [comment]
Great job - I generally agree with all of this and don't have any other ideas for design work to do.  

I'm going to mark this complete, since the brainstorming is complete, but we should parse each of these as further issues processing these.
