### ISSUE TITLE
gettin error with analytics command

### ISSUE THREAD

**Issue by thedrean** [18F/analytics.usa.gov#239]
I've suddenly been getting the error 

ERROR AFTER QUERYING: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

Not sure how to fix this, I think it has to do with the credentials key file?

Thanks

**Comment by konklone** [comment]
@thedrean Did you recently update to version 1.X of the code/module? When we moved from 0.x to 1.x, we did change some of the key processing code - it should be backwards-compatible with reading a .pem file from disk, but may not be if you're storing the key value in a string in Heroku.

If you log into the Google Developer Console, you can re-export new credentials in JSON format (Google's preferred format, changed since we started the project) and then follow the updated instructions in https://github.com/18f/analytics-reporter#setup to reference or format the key.

**Comment by thedrean** [comment]
Yes! Exporting the path to the json file did not work, extracting the key (making sure to replace the encoded \n and \u003d as well as ensuring zero unexpected space) worked! Thanks!

**Comment by konklone** [comment]
Glad to hear it!

If you can identify any bugfixes or improvements we should make there, please open an issue at https://github.com/18f/analytics-reporter/issues/new.
