### ISSUE TITLE
Don't count .exe web-based applications in Top Downloads

### ISSUE THREAD

**Issue by timwood** [18F/analytics.usa.gov#313]
Just noticed after the agency-level analytics dashboard was released today that the Commerce data (https://analytics.usa.gov/commerce/) includes three top downloads for "gate.exe" from a USPTO web property. Gate.exe appears to actually be a web-based application, not a downloadable .exe file.

Not sure whether the data tracking needs to be tweaked or the code which displays the data in the dashboard, so I'm submitting here.

Thanks!

**Comment by timwood** [comment]
Also:
* .php and .html examples under https://analytics.usa.gov/national-archives-records-administration/
* .asp under https://analytics.usa.gov/justice/
* .jsp and .cgi under https://analytics.usa.gov/education/

**Comment by gbinal** [comment]
Thanks - we're researching this in the upcoming sprint to resolve.

**Comment by tdlowden** [comment]
Hi @timwood. The analysis of this is as follows:

For .exe files, the DAP script that actually collects the data has .exe identified as an extension to record as a download in the autoTracker function. So that is desired.

For the other extensions that are not actually downloads (.php, .asp, etc) It appears that the agencies themselves have coded certain elements to pass into GA as download events. So, it is desired for them, since they coded it as such, although it does look a bit strange in the dashboard. We're going to communicate this with those agencies. Thanks for bringing this to our attention.

**Comment by tdlowden** [comment]
@timwood we did some more digging and found that some of the spurious downloads were coming in as a result of a regex bug in an older version of the code. We're trying to get everyone to update, and as a result, some of this should right itself.
