### ISSUE TITLE
d3 transitioning -bar chart to pie chart 

### ISSUE THREAD

**Issue by michalco** [18F/analytics.usa.gov#370]
hey,

what is the best way to change the grafic visualization from bar chart to pie chart ?

THX

**Comment by hbillings** [comment]
Hi @michalco, 
We don't have any plans to use pie charts, so all I can tell you is that you'll want to do something like this: https://bl.ocks.org/mbostock/3887235 (All the charts are rendered with D3.) Instead of adapting the current chart code, it might easier to write something from scratch against the data feeds found at the bottom of the page.
