### ISSUE TITLE
Convert from Http to Https

### ISSUE THREAD

**Issue by Mortimer77** [18F/analytics.usa.gov#427]
I want to convert from http to https.  My webserver is on Ubuntu.  I believe your analytics site code is running on Jekyll?  Can I add something to my _config.yml file to use SSL.   Has anyone setup a ssl cert and key on Jekyll?

**Comment by gbinal** [comment]
Hi @Mortimer77.  

Unfortunately, I believe it'll be more complicated than that.  You can find more info on converting to https at https://https.cio.gov/.  After that, some quick googling should turn up some good resources for you.  

I'm going to go ahead and close this issue since it's not germane to the project.  Good luck!
