### ISSUE TITLE
Custom Date Range / Average per Year

### ISSUE THREAD

**Issue by rbrady1848** [18F/analytics.usa.gov#448]
Hi Everyone, 

It would be great to be able to see which sites are the most visited during the year rather than just the last 30 days. A custom data range function would be ideal, but even an average per year and average this year would be great. - thanks!

**Comment by gbinal** [comment]
Hi, @rbrady1848.  Thanks a bunch for the idea.  

We're currently working on rolling out an API that will allow historical data to be queried and then aggregated, so that should help some with this.  

Otherwise though, our foreseeable roadmap is focused on refining the existing code and operations of this site, so we likely won't be expanding the GUI's functionality.  If we do though, we'll include this as a potential feature to add.  

Thanks again.

**Comment by rbrady1848** [comment]
That makes sense. Thanks for getting back to me!
