### ISSUE TITLE
USPS double counting sessions / users

### ISSUE THREAD

**Issue by thezedwards** [18F/analytics.usa.gov#512]
Howdy - first, great work on the federated analytics project - beautiful!

I noticed that in the top traffic sources (and in many reports) USPS.com is listed (aka self-referential to their subdomains and other sites). The USPS website is firing multiple instances of Google Tag Manager (this snippet @ https://builtwith.com/relationships/tag/GTM-MVCC8H) and multiple instances of Google Analytics, but it appears to not include the proper federated GA scripts. 

Also, one of the most popular pages in all of the federal government is this one @ https://informeddelivery.usps.com/box/pages/intro/start.action

That page is firing over 120 analytics and advertising pixels (as per an Evidon.com scan) and data are passing into all the major data platforms. It seems like someone should conduct an audit on the accounts the data is passing into and whether that's necessary (and who controls them). Here's a screenshot of the pixels firing - you'll notice Amazon is prominently firing on that page https://www.evernote.com/l/AH0OEV8uNmZLsry2yiHjqRH5qICKdEEc2Ew

There are some legacy pixels like https://uspshelp.widget.custhelp.com/euf/rightnow/RightNow.Client.js firing on the page with legacy mouse/typing listeners and generally just some odd stuff. 

I didn't know where else to report this, so apologies if this isn't the right location. Just seemed like something that someone on this analytics team should clean up a bit.

Thanks for all your awesome work!
-Zach

**Comment by tdlowden** [comment]
Hey Zach. Thanks for this detailed issue! Regarding the self-referrals, it's expected behavior. By default, our program breaks the session when a user travels to a new site or subdomain. The reason for this is that across most of the government, there are entirely different teams and in some cases buildings working on, for example: agency.gov vs component.agency.gov (a great example is nih.gov and nlm.nih.gov). In those cases, those teams very specifically want to know of referrals from other parts of the same root domain. In the USPS case, it may be that the movement across subdomains is more an intended journey, though. I'll reach out to them to let them know about cross-subdomain tracking options.

Regarding the second half of the issue, related to the pixels, I am going to cc @konklone here for visibility and pass this info on to USPS.

Thanks much for taking a detailed look at analytics.usa.gov!
