### ISSUE TITLE
Universal-Federated-Analytics Script issue

### ISSUE THREAD

**Issue by SanjayGupta-REISys** [18F/analytics.usa.gov#556]
## What kind of issue?
- [ ] Feature Request?
- [X ] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a <x kind of end user>, I would like to <y thing on the side>, so that I can <z provide the value of the change to the user>.

https://www.fai.gov is running into script error on every page.
[www.fai.gov-1559334406473.log](https://github.com/18F/analytics.usa.gov/files/3242779/www.fai.gov-1559334406473.log)
Please advise.
Syntax on our page $.getScript(dap.....url);

## Acceptance Criteria
- [ ]

**Comment by tdlowden** [comment]
Hi:

I don't see DAP script present on fai.gov at all; are you using a tag manager?  from what I can see in your log error, it's because you have included an invalid query parameter at the end of the `src` in the `<script>` tag. I see an underscore with a bunch of numbers, and that is not recognized by our system. Hope that helps. You can ask further questions by emailing dap@support.digitalgov.gov.
