### ISSUE TITLE
IE 11?

### ISSUE THREAD

**Issue by geramirez** [18F/analytics.usa.gov#562]
## What kind of issue?
- [ ] Feature Request?
- [x]  Bug

## User story
As a user accessing the site on IE11,
I would like to see the data on the site
So that I can get the information

## Acceptance Criteria
As a user accessing the site on IE11
When I navigate to the page
I can see all the charts

## Notes
Hey friends! The site doesn't load on IE11. Not sure if y'all decided not to support it. Just asking for some context.

**Comment by cyrialize** [comment]
Not sure how useful this is considering this issue is from 2019, but I figured I could chip in! My current company still supports IE11 so I have some experience with this. Looking at the console for IE11, we have the following issues:

![analytics-usa-gov-issues-ie11](https://user-images.githubusercontent.com/10124248/118377572-08accc80-b59c-11eb-9950-6ff7e1f51f24.JPG)

`Number.isNaN` is not supported within IE11: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN.

This could be fixed by just switching it to `isNan`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN.

For the other issue, `Expected identifier` this looks like it comes from these lines:
```
        1: [
            function (e, t, a) {
                var { _updateConfig: i, _defineCookieDomain: o, _defineAgencyCDsValues: n, gas: _, initTrackers: r, _initBasicTracker: s, createTracker: l, createYouTubeIFrames: O } = e("./Universal-Federated-Analytics.lib.js");
                i(), o(), n(), O(), s(), l(!0), r(), (window.gas = _);
            },
            { "./Universal-Federated-Analytics.lib.js": 2 },
        ],
```

The trailing comma at the end of `{ "./Universal-Federated-Analytics.lib.js": 2 },` causes issues: https://stackoverflow.com/questions/5158796/internet-explorer-errors-expected-identifier-and-object-expected. 

I'll try and dig further!

**Comment by cyrialize** [comment]
I tested out replacing instances of `Number.isNaN` with `isNan` and so far I don't see any apparent issues. 

I haven't worked with as complicated Jekyll websites as this one, so I'm still getting acquainted to the code base and workflow. I'm still learning to use tools like Babel as well, so maybe there's a Babel setting that could be set!
