### ISSUE TITLE
Mixed case URLs get normalized incorrectly & 404

### ISSUE THREAD

**Issue by mjsir911** [18F/analytics.usa.gov#886]
## What kind of issue?
- Bug

## User story
I went to [analytics.usa.gov](https://analytics.usa.gov/) today and clicked on the "Where Is Webb? NASA/Webb" link. It brought me to a 404 page on NASA's website.

This link: <http://jwst.nasa.gov/content/webblaunch/whereiswebb.html>

## Acceptance Criteria
- [ ] Should bring me to this link with the proper mixed case URL: <https://jwst.nasa.gov/content/webbLaunch/whereIsWebb.html>

## Notes
The source of this issue is in google analytics, the API is responding with the same normalization

This lowercase normalization was justified and marked as working as intended @ digital-analytics-program/gov-wide-code#10

The same lowercasing issue was run in to on 18F/analytics-reporter#84

**Comment by tdlowden** [comment]
Hi! Thanks for your issue.

You are correct that our data is standardized as lowercase. This is because upon collection, some sites take the step to resolve regardless of case. In the GA reporting interface, this causes disaggregation of Page URL data, which makes for harder analysis. The main goal of this data was always to help agencies create better UX for the public. The public dashboard has been very successful, but we haven't done anything to the data that would favor the public clicks on links over the cleanliness of data within the system for analysis.

So, you happened to have clicked on a link that is case sensitive (among the 6,000 participating websites, it's impossible to have universality), and therefore it 404s. That's unfortunate, but necessary for the cleanliness of our data internally. The standardized lowercase is intended. Apologies you encountered this issue, and I hope this provides context for our decision.

**Comment by tdlowden** [comment]
For what it's worth, we also remove "www." on all page URLs, and there are cases where some sites still require www. to resolve, so those links break as well.
